### ISSUE TITLE
Wrong Symbol for Console IO

### ISSUE THREAD

**Issue by M9909-AB** [AZHenley/hofstadter#3]
https://github.com/AZHenley/hofstadter/blob/1c30c61a8b22e38b86b6883e618dea7b27e63692/hofstadter.py#L38-L41

In the above lines from the interpreter, the symbol for console io is denoted by `#`. Either the documentation should be updated to reflect that or the interpreter should be updated to be consistent with the documentation.

**Comment by AZHenley** [comment]
Fixed in fdf29f1, thanks!
